### ISSUE TITLE
Change the fonts to Segoe

### ISSUE THREAD

**Issue by prajjwaldimri** [prajjwaldimri/GithubXamarin#20]
Should reflect the design language of Windows ecosystem

**Comment by satvikmaker** [comment]
I was checking it. But, its not a free font. We have to pay for it. [https://fonts.google.com/?query=segoe](https://fonts.google.com/?query=segoe).

Please provide the same, until then will close the issue.

**Comment by prajjwaldimri** [comment]
This is a nice alternative to Segoe: http://www.1001freefonts.com/webly_sleek.font

**Comment by prajjwaldimri** [comment]
But I think now that the app is cross-platform any fonts can be used!
