### ISSUE TITLE
What is UniversalMarkdown from project?

### ISSUE THREAD

**Issue by GitMoDu** [prajjwaldimri/GithubXamarin#23]
Tried opening the project for the first time, had a missing project and reference for a UniversalMarkdown.
Deleted those and it compiles and runs. Am I missing something?

**Comment by prajjwaldimri** [comment]
I don't know why but my VS didn't push the UniversalMarkdown project. It is a library for a tool that can render markdown in UWP and is created by Quinn Damerell. More info here: https://github.com/QuinnDamerell/UniversalMarkdown

**Comment by GitMoDu** [comment]
That's the info I was looking for. Try to fix the project app, it's very counter-productive to have a open-source project that needs hacking and google foo just to compile.

**Comment by prajjwaldimri** [comment]
Build Passing on AppVeyor. Should have no problems on local VS installations.

[![Build status](https://ci.appveyor.com/api/projects/status/ud7on9hsorejkbys?svg=true)](https://ci.appveyor.com/project/prajjwaldimri/githubuwp)

**Comment by GitMoDu** [comment]
Seems fixed, nice.
