### ISSUE TITLE
Plan for Scheduled Feature Releases

### ISSUE THREAD

**Issue by satvikmaker** [prajjwaldimri/GithubXamarin#31]
Hi,

Currently we have huge bunch of commits without a timeline or plan.
Tag feature/s against a release. Version the releases and develop features(and deliver fixed bugs) for the release.
Deliver release artifacts(.xap, .apk etc.,) as a part of the release.

**Comment by prajjwaldimri** [comment]
Yup, thought of doing that but I am currently very busy on #28. Can you do this one?

**Comment by prajjwaldimri** [comment]
We have to create the Wiki and README too. Also I think we should create milestones for the apps.

**Comment by satvikmaker** [comment]
Ok. I can do it. Have separate branch/tag for each release. Fix some bugs and some features and let's call it v1.0 🍡 Let me know what you are planning for.

**Comment by prajjwaldimri** [comment]
1.0.0 should have (For Windows and Android) (IOS excluded for now)

- Ability to view Repositories, Issues, Files, Gists, Notifications, Activities, Users
- Push Notifications
- Ability to edit user's repo, issues, files, gists
- Ability to display and edit comments on issues, repos etc.
