### ISSUE TITLE
Change name from GithubUWP to GithubXamarin

### ISSUE THREAD

**Issue by prajjwaldimri** [prajjwaldimri/GithubXamarin#32]
The app is cross-platform so the name GithubUWP makes no sense.

**Comment by prajjwaldimri** [comment]
Here are some tips if you are having some problems due to renaming

https://help.github.com/articles/renaming-a-repository/

**Comment by satvikmaker** [comment]
You said it'll be called Git-it?

**Comment by prajjwaldimri** [comment]
GitIt is the proposed name for the application
