### ISSUE TITLE
Features Plan - Release v1.0.0

### ISSUE THREAD

**Issue by satvikmaker** [prajjwaldimri/GithubXamarin#35]
**Features Planned for v1.0**

- [x] Ability to view Repositories, Issues, Files, Gists, Notifications, Activities, Users - 1
- [x] Push Notifications - 2

**Status and Timeline**

Feature | UWP | Android | Estimated Date
------------ | ------------ |------------- |-------------
1 - Views | done | done | 
2 - Notifications | done | done | 
3 - Edit | scheduled | scheduled | NA
4 - Comments | scheduled | scheduled | NA

**Comment by prajjwaldimri** [comment]
I think we should create a milestone for this too. What do you say @bozzmob ?

**Comment by satvikmaker** [comment]
Done!

**Comment by prajjwaldimri** [comment]
Editing feature cannot be done in this release and is moved to future releases.

**Comment by prajjwaldimri** [comment]
UWP app is now ready to be released.

**Comment by satvikmaker** [comment]
@prajjwaldimri go ahead... 3 2 1... Go...

**Comment by prajjwaldimri** [comment]
@bozzmob Have to build the Android version before launching in the store :P
