### ISSUE TITLE
Text is missing from events

### ISSUE THREAD

**Issue by cristianst85** [prajjwaldimri/GithubXamarin#88]
Hi,

I've attached two screenshots that shows this bug.
In this case probably the culprit is that the original text contains an emoticon.

**GitHub events as shown in browser**
![github-events](https://cloud.githubusercontent.com/assets/12585988/25719685/e7b5f64e-3112-11e7-92b5-e642472b001f.png)

**GitHub events as shown by GitIt**
![wp_ss_20170504_0005](https://cloud.githubusercontent.com/assets/12585988/25719686/e7dc514a-3112-11e7-80b6-3846fa946d72.png)

Also, the time is off by one hour (my timezone is EEST -  Eastern European Summer Time / UTC+3).

Thanks!

**Comment by prajjwaldimri** [comment]
Hmm, this seems weird. The top comment and the 3rd comment are basically the same thing and one is getting displayed and other is not. :thinking:  Have to take a look into this. 

Meanwhile, if anyone wants to take a look into this, the string for this type of event is supplied from here: https://github.com/prajjwaldimri/GithubXamarin/blob/master/GithubXamarin.Core/Converters/EventToStringConverter.cs#L40 

Relevant github api link: https://developer.github.com/v3/activity/events/types/#issuecommentevent

Also about the timezone, it is provided by github api directly and the app is not doing any time conversions, so could be a problem with system time.
